### ISSUE TITLE
python run_experiments.py --exp 101 does not launch the experiments

### ISSUE THREAD

**Issue by dbash** [lhoyer/DAFormer#15]
Hi!

I need to run the source-only experiment with your model. However, running python run_experiments.py --exp 101 does not launch the training procedure. Here is what it prints: 
Run job 220315_1238_zerowaste2zerowaste_source-only_segformer_mitb5_poly10warm_s0_9e0a0
/projectnb2/ivc-ml/dbash/code/DAFormer/mmseg/models/backbones/mix_transformer.py:214: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
/projectnb/ivc-ml/dbash/.conda/envs/daformer/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py:118: UserWarning: init_cfg without layer key, if you do not define override key either, this init_cfg will do nothing
  warnings.warn(

After that, it just exits. I was wondering if I did something wrong here and if you could help me with this issue. The only changes I've made is I commented out L421-428 in experiments.py.

Thank you for your time!

**Comment by lhoyer** [comment]
Hi Dina,

Experiment 101 is only supposed to test if all configurations launch properly. Therefore, it is set to only train for two iterations and to only report errors. The behavior you are describing is intended. 

To run a proper training, please use experiment 7 for example. To train source-only, you can just set `uda = 'source-only'` in line 369. 

Best,
Lukas

**Comment by dbash** [comment]
Thank you for a quick response!
