### ISSUE TITLE
src.loss_imnet_feat_dist is nan

### ISSUE THREAD

**Issue by Haochen-Wang409** [lhoyer/DAFormer#17]
Hi, thanks for your excellent work!
However, when I tried to train DAFormer on GTA5 to Cityscapes benchmark, I found ```src.loss_imnet_feat_dist``` is ```nan``` while training. Since the final result is expected (68.3 mIoU), I'm a little bit confused.

**Comment by lhoyer** [comment]
Thanks for your interest in our work! 
Please, have a look at issue #11. It should clarify your question.

**Comment by Haochen-Wang409** [comment]
Thanks a lot for your answer!

**Comment by kaigelee** [comment]
> Hi, thanks for your excellent work! However, when I tried to train DAFormer on GTA5 to Cityscapes benchmark, I found `src.loss_imnet_feat_dist` is `nan` while training. Since the final result is expected (68.3 mIoU), I'm a little bit confused.

My decode.loss_seg is also nan, could you help me fix it?

**Comment by lhoyer** [comment]
> > Hi, thanks for your excellent work! However, when I tried to train DAFormer on GTA5 to Cityscapes benchmark, I found `src.loss_imnet_feat_dist` is `nan` while training. Since the final result is expected (68.3 mIoU), I'm a little bit confused.
> 
> My decode.loss_seg is also nan, could you help me fix it?

This is a separate issue. Please continue the discussion in issue #22.

**Comment by lhoyer** [comment]
> > Hi, thanks for your excellent work! However, when I tried to train DAFormer on GTA5 to Cityscapes benchmark, I found `src.loss_imnet_feat_dist` is `nan` while training. Since the final result is expected (68.3 mIoU), I'm a little bit confused.
> 
> My decode.loss_seg is also nan, could you help me fix it?

This is a separate issue. Please continue the discussion in issue #22.
