### ISSUE TITLE
Invitation of contributing to MMSegmentation. 

### ISSUE THREAD

**Issue by MengzhangLI** [lhoyer/DAFormer#2]
Hi, thanks for your excellent work. 

We are members of [OpenMMLab](https://github.com/open-mmlab) whose codebase [MMSegmentation](https://github.com/open-mmlab/mmsegmentation) is related with your excellent work. Would you like to join us to make a pr about your repo? Currnetly our tasks are all fully supervised segmentation. I think if DAFormer is supported, more researchers could use and cite this method.

Looking forward to your reply! 

Best,

**Comment by lhoyer** [comment]
Hi, Thanks a lot for providing the great MMSegmentation framework and for inviting us to contribute. 
Unfortunately, we are currently too busy to refactor our code for a PR at the moment. If the situation changes, we will let you know.

**Comment by MengzhangLI** [comment]
OK, got it.

Feel free to contact us if you want to make pr or give any suggestions on OpenMMLab codebases.

Best,

**Comment by MengzhangLI** [comment]
Congrats for acceptance of CVPR'2022. 

We are going to add features and some research exploration of domain adaptation in MMSegmentation. Looking forward to cooperate and discuss with you.

**Comment by lhoyer** [comment]
Thanks a lot!

I'm happy to hear that. Feel free to contact me via e-mail if you have specific questions.
