### ISSUE TITLE
Questions about the data stream

### ISSUE THREAD

**Issue by Yulu-gan** [lhoyer/DAFormer#25]
Thanks for your solid and excellent work! but I have some questions. Under the mmseg framework, where did you call mmseg / models / uda / dacs.py,  and RSC as wll as the whole backbone training process are all in dacs.py?  I'm looking forward to your reply.

**Comment by Yulu-gan** [comment]
I've found '**_dacs_a999_fdthings.py_**' under .../_base_/uda ， is this the config we use? but I find  '**_name_uda_**' in '_**gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py**_' is **_'dacs_a999_fd_things_rcs0.01_cpl_**'

**Comment by lhoyer** [comment]
Thank you for your interest in our work!

If you want to train DAFormer with the standalone config file, please have a look at: https://github.com/lhoyer/DAFormer/blob/master/configs/daformer/gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py 

You can find the relevant config flags for the feature distance in line 21-23 and the config flags for rare class sampling in line 30-31.

The feature distance is implemented here: https://github.com/lhoyer/DAFormer/blob/master/mmseg/models/uda/dacs.py#L157

The rare class sampling is implemented here: https://github.com/lhoyer/DAFormer/blob/master/mmseg/datasets/uda_dataset.py

The file configs/base/uda/dacs_a999_fdthings.py is only used for automatic config file generation using experiments.py. So, you can ignore is when you use configs/daformer/gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py

**Comment by Yulu-gan** [comment]
Got it. Thank you for your patience.
