### ISSUE TITLE
target ann_dir

### ISSUE THREAD

**Issue by Changryeol-Jeon** [lhoyer/DAFormer#34]
https://github.com/lhoyer/DAFormer/blob/8d6e710700ff5e6a053c77bfe384ba44d4672cbe/configs/_base_/datasets/uda_gta_to_cityscapes_512x512.py#L59-L64

why target train data annotation is needed?? Shouldn't DA not have that part?

**Comment by lhoyer** [comment]
This is a relict of the original dataset structure of the mmseg framework, which was designed for supervised training. The target ground truth is never used during UDA training.

**Comment by Changryeol-Jeon** [comment]
thanks a lot!
