### ISSUE TITLE
imnet_feature_dist_classes=[6, 7, 11, 12, 13, 14, 15, 16, 17, 18]

### ISSUE THREAD

**Issue by creater-zq** [lhoyer/DAFormer#39]
Hello! 
* How to choose these classes in experiment? such as`traffic light`、`traffic sign`, etc.
* Because in training,  I observed `src.loss_imnet_feat_dist: nan`.
* thanks!

**Comment by lhoyer** [comment]
Hello,

1. These classes are chosen to be thing-classes (countable objects such as car or traffic light) in contrast to stuff-classes (background regions such as road). Please, also have a look at Sec. B in the Supplement: "For the distinction of thing- and stuff-classes, we follow the definition by Caesar et al. [4]. Applied to Cityscapes, thing-classes are traffic light, traffic sign, person, rider, car, truck, bus, train, motorcycle, and bicycle and stuff-classes are road, sidewalk, building, wall, fence, pole, vegetation, terrain, and sky."
[4] Holger Caesar, Jasper Uijlings, and Vittorio Ferrari. Coco-stuff: Thing and stuff classes in context. In IEEE Conf. Comput. Vis. Pattern Recog., pages 1209–1218, 2018.
2. Please, have a look at Issue #11.
