### ISSUE TITLE
The unreproducible results

### ISSUE THREAD

**Issue by JunXieFront** [lhoyer/DAFormer#40]
Dear author, thanks for your amazing contributions in DA Segmentation task. During the process of running the code， I find that I can't get same result even if setting the same random seed. There is only slight difference (the acc_seg and decode loss) during the early training process, However, after thousands of iterations, difference can not be igonorable.
Could you help me how to fix the problem? thank you very much!

**Comment by lhoyer** [comment]
Thank you for your interest in our work!

Could you please provide some additional information so that I can try to help with debugging your problem:

1. Have you carefully followed the instructions in the readme to set up the environment? Do you use the same library versions as listed in the readme and the requirements.txt? Have you preprocessed the datasets? 
2. Which command have you run to train DAFormer? On which datasets are you working?
3. What is the performance difference that you have observed? Could you please provide your training log?

**Comment by JunXieFront** [comment]
Thanks for your reply!
For the environment, I have carefully followed your instructions to set up. 
For the command, I used "python run_experiments.py --config configs/daformer/gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py"
I find that "decode.loss" and "decode.acc_seg" are different even though the same iteration number. For example, when the iteration number is 1200, In the "220816_0929" train log, the decode.loss_seg is 0.2722, however in the "220816_0856" train log, the decode.loss_seg is 0.2724.
the slight difference can lead to different final outcome, I don't know if that's normal.
May be the floating-point number calculation or just my wrong operations caused the difference? 
The train log is included in the mailbox attachment。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "lhoyer/DAFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lhoyer/DAFormer] The unreproducible results (Issue #40)





 
Thank you for your interest in our work!
 
Could you please provide some additional information so that I can try to help with debugging your problem:
  
Have you carefully followed the instructions in the readme to set up the environment? Do you use the same library versions as listed in the readme and the requirements.txt? Have you preprocessed the datasets?
 
Which command have you run to train DAFormer? On which datasets are you working?
 
What is the performance difference that you have observed? Could you please provide your training log?

**Comment by lhoyer** [comment]
Even with the same seed, the results will differ between different runs and won't reproduce exactly. This is because some PyTorch functions are not deterministic. So, varying results are expected. Still, the mIoU should be roughly between 66 and 69 mIoU.

I cannot find the attachment. Possibly, you need to upload it on the Github page directly instead of replying via email.

**Comment by Wenlve-Zhou** [comment]
> Thanks for your reply! For the environment, I have carefully followed your instructions to set up. For the command, I used "python run_experiments.py --config configs/daformer/gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py" I find that "decode.loss" and "decode.acc_seg" are different even though the same iteration number. For example, when the iteration number is 1200, In the "220816_0929" train log, the decode.loss_seg is 0.2722, however in the "220816_0856" train log, the decode.loss_seg is 0.2724. the slight difference can lead to different final outcome, I don't know if that's normal. May be the floating-point number calculation or just my wrong operations caused the difference? The train log is included in the mailbox attachment。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "lhoyer/DAFormer" ***@***.***&gt;; 发送时间:&nbsp;2022年8月15日(星期一) 下午3:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [lhoyer/DAFormer] The unreproducible results (Issue #40) Thank you for your interest in our work! Could you please provide some additional information so that I can try to help with debugging your problem: Have you carefully followed the instructions in the readme to set up the environment? Do you use the same library versions as listed in the readme and the requirements.txt? Have you preprocessed the datasets? Which command have you run to train DAFormer? On which datasets are you working? What is the performance difference that you have observed? Could you please provide your training log? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hello! I also have this problem. Have you solved it?
