### ISSUE TITLE
why not support Multi-GPU? is it not necessary for UDA?

### ISSUE THREAD

**Issue by fuweifu-vtoo** [lhoyer/DAFormer#43]
Have you read code for SoftTeacher? This code seems to have nothing to do with ddp_train_gans, but it still use multi-gpu training UDA model.
[https://github.com/lhoyer/DAFormer/issues/9](url)

**Comment by fuweifu-vtoo** [comment]
It feels like your code supports multi-gpu training natively because you use the DDP wrapper.
You just need to start the command with OMP_NUM_THREADS=1 python3 -m torch.distributed.launch ?

**Comment by xiaoachen98** [comment]
> Have you read code for SoftTeacher? This code seems to have nothing to do with ddp_train_gans, but it still use multi-gpu training UDA model. [https://github.com/lhoyer/DAFormer/issues/9](url)

We have supported the Multi-GPU training procedure. You can follow our work and repo (https://github.com/xiaoachen98/DDB).

**Comment by lhoyer** [comment]
@fuweifu-vtoo DAFormer can be trained on a single GPU within 16 hours. As this is a very reasonable training time, we opted for simplicity and did not use Multi-GPU training. The instructions on how to generally use Multi-GPU training can be found in the mmsegmentation repository. Please, also check that the model update of the momentum teacher is compatible.

@xiaoachen98 Thanks for sharing your code with Multi-GPU training.
