### ISSUE TITLE
Wrong download link of the Cityscapes→DarkZurich Checkpoint

### ISSUE THREAD

**Issue by XiaRho** [lhoyer/DAFormer#44]
The download link of the Cityscapes→DarkZurich Checkpoint you provided for DAFormer is https://drive.google.com/file/d/1z4QyN6HG2XYPJ8v4n_rdvXR7--tIcC9Y/view?usp=sharing (
csHR2dzurHR_hrda_97e26.tar.gz), which is the method of HRDA not the DAFormer. You seem to put the download link of another method (HRDA) here.

**Comment by lhoyer** [comment]
I fixed the download link.
