### ISSUE TITLE
Compatible with earlier MMSEG versions

### ISSUE THREAD

**Issue by LuPaoPao** [lhoyer/DAFormer#49]
My version of cuda (11.3) does not enable me to install lower versions of MMCV (1.3.7) and this code is not compatible with higher versions of mmsegmentation. So how do I handle this?

**Comment by lhoyer** [comment]
Hi @LuPaoPao,

Thank you for your interest in our work. You could either try to downgrade cuda or upgrade mmcv. The latter might require to also adapt some code in the mmseg folder of DAFormer to the newer mmcv version. Please, have a look at the history of https://github.com/open-mmlab/mmsegmentation to see how they handled the upgrade of mmcv after mmseg version 0.16.0.

Best,
Lukas
