### ISSUE TITLE
performance without mix augmentation

### ISSUE THREAD

**Issue by valencebond** [lhoyer/DAFormer#5]
Thanks for your detailed codes. Is there any ablation study about performance without DACS augmentation? I wonder if online pseudo-label generation is very dependent on augmentation. I also conduct the experiments without DACS augmentation. The performance is only 37.

**Comment by lhoyer** [comment]
Thanks for your interest in our paper. We did not run an ablation of the DACS augmentation (color jitter + blur + ClassMix) as it is part of our baseline framework and not the focus of this work itself. However, I would expect a significant performance degradation if you disable color jitter, blur, and ClassMix as the augmentations are a crucial part of the consistency training.
