### ISSUE TITLE
About 'sample_class_stats.json'

### ISSUE THREAD

**Issue by liwei1101** [lhoyer/DAFormer#50]
Hello! Thank you for your wonderful work.

I'm having problems with missing files when reproducing.

Where can I get the 'sample_class_stats.json' please?

**Comment by lhoyer** [comment]
Hi @liwei1101, 
Thank you for your interest in our work. Probably, you didn't run the data processing as described in the README.md:

Finally, please run the following scripts to convert the label IDs to the train IDs and to generate the class index for RCS:

```bash
python tools/convert_datasets/gta.py data/gta --nproc 8
python tools/convert_datasets/cityscapes.py data/cityscapes --nproc 8
python tools/convert_datasets/synthia.py data/synthia/ --nproc 8
```
