### ISSUE TITLE
code about "Rare Class Sampling (RCS)"

### ISSUE THREAD

**Issue by yuheyuan** [lhoyer/DAFormer#53]
hi, I want to find the code about Rare Class Sampling module. But I don't find it. I am not at coding.
So I want to ask where can find your Rare Class Sampling module. I want to use it in other job because this is a very potential module.

**Comment by lhoyer** [comment]
You can find the implementation of RCS here: https://github.com/lhoyer/DAFormer/blob/master/mmseg/datasets/uda_dataset.py
The class statistics are collected during the data conversion: https://github.com/lhoyer/DAFormer/blob/master/tools/convert_datasets/gta.py

**Comment by yuheyuan** [comment]
> You can find the implementation of RCS here: https://github.com/lhoyer/DAFormer/blob/master/mmseg/datasets/uda_dataset.py The class statistics are collected during the data conversion: https://github.com/lhoyer/DAFormer/blob/master/tools/convert_datasets/gta.py

Oh, thank you 
Another question, your recent paper 《MIC: Masked Image Consistency for Context-Enhanced Domain Adaptation》
![image](https://user-images.githubusercontent.com/39433014/205850943-7f361533-a735-4671-aa41-345c70a4b9ad.png)

You use MIC module.So I want to ask if you use MIC module only. because HRDA and DAFormer all use RCS module.

**Comment by lhoyer** [comment]
For a fair comparison, MIC(DAFormer) and MIC(HRDA) both use RCS because DAFormer and HRDA use RCS as well. MIC(Adversarial) does not use RCS because "Adversarial" does not use RCS.

**Comment by lhoyer** [comment]
You can find the corresponding configurations here: https://github.com/lhoyer/MIC/blob/34dad1283c44e4cd269ce756e2b686d418d87c22/seg/experiments.py#L417 
The relevant variable is `rcs_T`.
