### ISSUE TITLE
Different batch sizes for source and target data

### ISSUE THREAD

**Issue by kaigelee** [lhoyer/DAFormer#54]
I'm wondering how I can adopt a batchsize where source domain and target domain images are inconsistent?
e.g., for GTA-V, batchsize = 4 while for cityscapes, batchsize = 2.

Looking forward to your answer!
Thank you.

**Comment by lhoyer** [comment]
Hi @kaigelee,

This behavior is not supported by this repository out-of-the-box. To implement it, you probably need to adapt https://github.com/lhoyer/DAFormer/blob/master/mmseg/datasets/builder.py and https://github.com/lhoyer/DAFormer/blob/master/mmseg/datasets/uda_dataset.py.

Best,
Lukas
