### ISSUE TITLE
How to pre-process other datasets to adapt to daformer

### ISSUE THREAD

**Issue by libobo-1998** [lhoyer/DAFormer#55]

**Comment by lhoyer** [comment]
For pre-processing other datasets, you can copy and modify the conversion script of GTA (https://github.com/lhoyer/DAFormer/blob/master/tools/convert_datasets/gta.py) according to the specifics of the other dataset (e.g. label ID definition).

**Comment by libobo-1998** [comment]
We've solved that problem, thank you！
