### ISSUE TITLE
visuial of t-sne

### ISSUE THREAD

**Issue by yuheyuan** [lhoyer/DAFormer#56]
![image](https://user-images.githubusercontent.com/39433014/222371713-92153612-2d04-409b-bee8-7a50afed1e56.png)
I think the picture in your paper is so cool.
I want to use t-sne to produce the same effiect.But I don't know how to realize it.
Could you offer some code or detial about it.
Maybe it's too long because you finish this work last year.
If you can reply me. Very appreciated

**Comment by lhoyer** [comment]
We have generated these plots using https://github.com/DmitryUlyanov/Multicore-TSNE. Specifically, we have inferred the bottleneck features of the model, filtered out feature pixels that contain different ground truth classes within the feature pixel region (this can happen as the feature map has a lower resolution as the ground truth semantic segmentation), calculated the TSNE embedding of these features, and colored them according to the ground truth class of that feature pixel,

**Comment by leo-hao** [comment]
> We have generated these plots using https://github.com/DmitryUlyanov/Multicore-TSNE. Specifically, we have inferred the bottleneck features of the model, filtered out feature pixels that contain different ground truth classes within the feature pixel region (this can happen as the feature map has a lower resolution as the ground truth semantic segmentation), calculated the TSNE embedding of these features, and colored them according to the ground truth class of that feature pixel,

Dear Lukas Hoyer,

I hope this message finds you well. I want to express my gratitude for your open-source work, which has been instrumental in my research during my Master's program. I recently came across the feature distribution map in your paper, and it would greatly enhance the quality of my Master's thesis.

Specifically, I have used encode_decode(img, img_meta) to obtain the feature maps from the validation set of the Cityscapes dataset. The shape of the feature maps is (1, 19, 1024, 2048). I have also used inference_segmentor(model, img_path) to obtain the labels, which have a shape of (1024, 2048). However, I have encountered an issue in using t-SNE to visualize the feature distribution of the feature maps with different colors.

I truly appreciate your contributions to the community and admire your work. If it's convenient for you, could you please provide some guidance on how to configure t-SNE to properly display the feature distribution of the feature maps? Thank you so much for your time, and I look forward to hearing from you.

Best regards,

Hao Liu

**Comment by leo-hao** [comment]
> We have generated these plots using https://github.com/DmitryUlyanov/Multicore-TSNE. Specifically, we have inferred the bottleneck features of the model, filtered out feature pixels that contain different ground truth classes within the feature pixel region (this can happen as the feature map has a lower resolution as the ground truth semantic segmentation), calculated the TSNE embedding of these features, and colored them according to the ground truth class of that feature pixel,

I am conducting some visualization experiments using the weights of segformer-mitb0 in mmsegmeantation. I downsampled the feature maps of 10 images from (10, 19, 1024, 2048) to (10, 19, 32, 32), and the labels as well, from (10, 1024, 2048) to (10, 32, 32). Then I used tsne to reduce the dimensionality of (32*32, 19), and visualized the results. However, I was not satisfied with the outcome. Could you please kindly share with me how you did the experiment? I would appreciate your reply very much!
![tsne32x32x10](https://user-images.githubusercontent.com/20486586/228501518-27b549fa-4ab7-491a-bcb2-383139a60f59.png)

**Comment by yuheyuan** [comment]
> We have generated these plots using https://github.com/DmitryUlyanov/Multicore-TSNE. Specifically, we have inferred the bottleneck features of the model, filtered out feature pixels that contain different ground truth classes within the feature pixel region (this can happen as the feature map has a lower resolution as the ground truth semantic segmentation), calculated the TSNE embedding of these features, and colored them according to the ground truth class of that feature pixel,

Hi， I sucee install multicore-TSNE.
Then , I have some problems about the detials.
I use tsne in the test.py.
and the data are all too big, it spend too many time(9 hours), it dosen't visual.
do you remeber you use data to visual.
for example, 
```txt
the feature size = torch.size([2097152, 19])
```
it's too big. Do you resize the feature.
