### ISSUE TITLE
Questions about training on custom dataset

### ISSUE THREAD

**Issue by qubewx** [lhoyer/DAFormer#57]
When I was training, I found that the accuracy of verification set was very high at the beginning and then it began to decline. Besides, the segmentation graph generated by demo-image.py was not effective. Besides, I did not see the Lt loss function marked in the graph on the code. Thank you

**Comment by qubewx** [comment]
[
[20230301_211002.log](https://github.com/lhoyer/DAFormer/files/10931162/20230301_211002.log)
Thanks for your reply. The above is my log file,the 4347th row shows the 8000 epoch' result,89% .But after this,the aACC  always decline.Besize, Can you send me your train log?Thank you very much!

**Comment by lhoyer** [comment]
It seems that you only train with two classes on custom datasets. Without knowing your setup, I cannot provide insights what causes the issues, which you observe. The DAFormer checkpoints from https://github.com/lhoyer/DAFormer#checkpoints are accompanied with logs.
