### ISSUE TITLE
What's the "IMTRv21_5"?

### ISSUE THREAD

**Issue by nightrain-vampire** [lhoyer/DAFormer#58]
In "configs/_base_/models/segformer.py", there is the code:
`model = dict(
......
backbone=dict(type='IMTRv21_5', style='pytorch'),
......
)`

I can not find the definition of IMTRv21_5 in either MMsegmentation's backbone library or in the author's code. Can anyone give me some guidance?

**Comment by lhoyer** [comment]
This is an internal name of the original SegFormer repo https://github.com/NVlabs/SegFormer and is not used in this repo. In this repo, `type='IMTRv21_5'` is overriden by the used child configs such as https://github.com/lhoyer/DAFormer/blob/master/configs/_base_/models/segformer_b5.py or https://github.com/lhoyer/DAFormer/blob/master/configs/_base_/models/daformer_conv1_mitb5.py.
