### ISSUE TITLE
Test method

### ISSUE THREAD

**Issue by HKQX** [lhoyer/DAFormer#62]
Dear authors, thank you for your outstanding work. The GTA->cityscape dataset was tested with 500 validation sets and the result was 68.85. Is 68.3 the predicted result from submitting to cityscape's official website?Looking forward to your reply

**Comment by lhoyer** [comment]
Hello @HKQX,

Thank you for your interest in our work! The results reported in the paper are averaged over 3 checkpoints with different random seeds for the training. The provided checkpoint is one of them. The validation is done locally without using the Cityscapes server.
