### ISSUE TITLE
MiT-B3 log

### ISSUE THREAD

**Issue by Jjomaeng** [lhoyer/DAFormer#66]
I was impressed with the DAFORMER you implemented.

I'd like to check the result of using MiT-B3 as backbone, so could you give me a log?

**Comment by lhoyer** [comment]
Hi @Jjomaeng,

Thank you for your interest in our work. We only trained DAFormer with a MiT-B5 backbone. Therefore, I don't have logs for DAFormer with MiT-B3.

Best,
Lukas

**Comment by SSSilvester** [comment]
Hello, have you been able to run it successfully? I'm facing some difficulties and would appreciate it if we could exchange ideas.
