### ISSUE TITLE
About the threshold

### ISSUE THREAD

**Issue by JinYoon002** [lhoyer/DAFormer#70]
Hi sir,

In your paper, it says "Here, we use the ratio of pixels exceeding a threshold τ of the maximum softmax probability".

Where could I find the value of the threshold in your codebase? Thanks

Kindly Regards

**Comment by lhoyer** [comment]
You can find the value here: https://github.com/lhoyer/DAFormer/blob/6d87ab857665f3c5a4b481c1da3fb5e227792830/configs/_base_/uda/dacs.py#L10
