### ISSUE TITLE
resizing to 1024,512 cityscape

### ISSUE THREAD

**Issue by elhamAm** [lhoyer/DAFormer#72]
Thank you for your great work!
where do you resize and how do you resize the semantic labels for cityscape to 1024, 512? As I understand since the labels are discrete the resizing should not involve any interpolation, right? So I was wondering how you do this.

**Comment by VdaylightV** [comment]
Hello, I find something in the code.
In the class `Resize` in file `mmseg/datasets/pipelines/transforms.py`, the resizing of the label adopted the `nearest`  interpolation mode in `_resize_seg` method of that class.
