### ISSUE TITLE
Training weights cannot be downloaded

### ISSUE THREAD

**Issue by jiuyuzhang** [lhoyer/DAFormer#74]
Hi, is there any other way to download the training weights, I can't open the link in google cloud drive

**Comment by lhoyer** [comment]
Can you please specify which weights you cannot download?

**Comment by jiuyuzhang** [comment]
MiT weights in download_checkpoints.sh，thanks,website shows no permission

**Comment by lhoyer** [comment]
It looks like the authors of [SegFormer](https://github.com/NVlabs/SegFormer) changed the permissions of the Google Drive files. However, you can still download them from their OneDrive: https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/Ept_oetyUGFCsZTKiL_90kUBy5jmPV65O5rJInsnRCDWJQ?e=CvGohw

**Comment by jiuyuzhang** [comment]
Thank you very much. It's solved.

**Comment by Gina699** [comment]
Dear Dr.Hoyer,i opened the website you answered above ，but i found that there are two different versions for each Mit-Bx,could i konw which should we use for DAFormer?
![image](https://github.com/lhoyer/DAFormer/assets/58212495/11f15e44-d53a-48f8-be0b-e784dd1eee32)

**Comment by lhoyer** [comment]
Hi @Gina699,

I'm sorry. I shared the wrong OneDrive link. Please, use this one instead: https://connecthkuhk-my.sharepoint.com/personal/xieenze_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fxieenze%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fsegformer%2Fpretrained%5Fmodels&ga=1

**Comment by lhoyer** [comment]
Does this link work for you: https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ

**Comment by Gina699** [comment]
Yes,it works.You are responsible sooooooo much!DAFormer and HRDA inspire me a lot,and i am looking forward to seeing your following academic results.

**Comment by lhoyer** [comment]
Thank you!

**Comment by SSSilvester** [comment]
> Yes,it works.You are responsible sooooooo much!DAFormer and HRDA inspire me a lot,and i am looking forward to seeing your following academic results.
Hello, have you been able to run it successfully? I'm facing some difficulties and would appreciate it if we could exchange ideas.
