### ISSUE TITLE
Questions about CNNs-based results better than Transformer-based results 

### ISSUE THREAD

**Issue by jetitime** [lhoyer/DAFormer#77]
Dear author,
  Sorry to distrub you. Thanks for your great work in UDA.
  I want to reimplement the UDA method you given to solve remote sensing UDA in semantic segmentation task. However, I found that the UDA results based on DeeplabV2 worked better than on Transformer（both on Segformer and on MiTb5+decoder you put forward). I have no idea about the strange result. Can you give me some advice whether because I didn't operate correct or because the datasets have different feature?
  I attached the results of the experiment and the running log. Looking forward to your reply. Thank you very much.
![image](https://github.com/lhoyer/DAFormer/assets/101321788/2cc4a34e-df78-4ee1-bec7-47e2f1708c37)

[MiTb5+MLP.log](https://github.com/lhoyer/DAFormer/files/12843927/MiTb5%2BMLP.log)
[DeepLabV2_R101.log](https://github.com/lhoyer/DAFormer/files/12843928/DeepLabV2_R101.log)
[MiTb5+Context-aware Fusion.log](https://github.com/lhoyer/DAFormer/files/12843929/MiTb5%2BContext-aware.Fusion.log)

**Comment by XZhang878** [comment]
Dear @jetitime
 Excuse me, how do you generate sample_class_stats.json when using DAFormer to implement remote sensing UDA? Thanks

**Comment by jetitime** [comment]
@XZhang878, maybe you can refer to the code as shown in the image to generate a json file.
![json](https://github.com/lhoyer/DAFormer/assets/101321788/01f29271-ee9c-4b4b-b9d9-a77b85cfb891)

**Comment by XZhang878** [comment]
@jetitime, Thank you very much for your help, but when I carry out the Potedam IR-R-G to Vaihingen task again, I will set the parameters of the experiment according to the log file you provided during the experiment. But my miou is only about 30%. Can you help me solve this problem? Thank you very much.

**Comment by jetitime** [comment]
@XZhang878 , It occurred to me that the reason for the lower reproducibility results might be because of the pretrained weight files. I used the MiT pretrained weight file trained on the ImageNet-1k data set officially provided by SegFormer. 

Url: https://connecthkuhk-my.sharepoint.com/personal/xieenze_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fxieenze%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fsegformer%2Fpretrained%5Fmodels&ga=1

Hope this  will helps you.
