### ISSUE TITLE
Question about default .py for config

### ISSUE THREAD

**Issue by ShenZheng2000** [lhoyer/DAFormer#78]
Hello, author! I appreciate your excellent work. 

I've noticed that all experiments use [this configuration file](https://github.com/lhoyer/DAFormer/blob/master/configs/daformer/gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py) as a base and only modify the parameters under the `# Meta Information for Result Analysis` section.

Now, I would like to introduce some custom modifications to the model and potentially create another .py file similar to the current one. 

However, I'm unsure about how to import this new .py file for model training. Could you provide some guidance on this matter?

**Comment by ShenZheng2000** [comment]
I have found the code specifying config .py for training. Hence, I will close this issue for now.

**Comment by SSSilvester** [comment]
你好，请问你跑通了吗？我遇到了一些困难，可以相互交流一下吗？
