### ISSUE TITLE
MIT weight无法获得

### ISSUE THREAD

**Issue by Ronever** [lhoyer/DAFormer#84]

**Comment by lhoyer** [comment]
It looks like the authors of [SegFormer](https://github.com/NVlabs/SegFormer) changed the permissions of the Google Drive files. However, you can still download them from their OneDrive: https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ, which is provided in https://github.com/NVlabs/SegFormer#training.

**Comment by lhoyer** [comment]
I updated the instructions in the README

**Comment by Ronever** [comment]
Thank you. You are a nice man.



---原始邮件---
发件人: "Lukas ***@***.***&gt;
发送时间: 2023年12月13日(周三) 下午5:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lhoyer/DAFormer] MIT weight无法获得 (Issue #84)




 
I updated the instructions in the README
