### ISSUE TITLE
bad results

### ISSUE THREAD

**Issue by SSSilvester** [lhoyer/DAFormer#91]
Hello,

I have diligently adhered to the content outlined in the readme, downloading 'mit_b5' and placing it within the 'pretrained' folder. Additionally, I have conducted data preprocessing in accordance with the method you suggested. Despite these steps, after completing 40,000 iterations, the Mean Intersection over Union (mIoU) score I am able to attain is a mere 26. I have devoted considerable time to meticulously scrutinizing my procedures but remain at a loss as to what could be causing this issue. Would you kindly offer your expertise and assistance? Your work is greatly appreciated, and I thank you in advance for your help.

**Comment by SSSilvester** [comment]
My logs are coming up with a lot of exception initialization messages.

model.backbone.patch_embed1.proj.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed1.proj.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed1.norm.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed1.norm.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed2.proj.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed2.proj.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed2.norm.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed2.norm.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed3.proj.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed3.proj.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed3.norm.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed3.norm.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed4.proj.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed4.proj.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed4.norm.weight - The value is the same before and after calling `init_weights` of DACS  
model.backbone.patch_embed4.norm.bias - The value is the same before and after calling `init_weights` of DACS  
model.backbone.block1.0.norm1.weight - The value is the same before and after calling `init_weights` of DACS

**Comment by 1335546270** [comment]
Hello! I also have this problem. Have you solved it?
